# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34e309505efe7205484fd3ec4459f2dbfdfc188d46f2c7b7717fda077dab47323fceb2238d797e06ab74de00fc1ccd3507dd156c97dacdbc352baf8f19d7543c

test:
  secret_key_base: d1cf9748efd5819d6eed2d4ed82cff7bb16627487be6206cdf95e7e2b4c41e1c65baf2c0cb4b781966ebccaea40419bb7addc39e4ed4184f47f8626dde0fe7ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
